# Generated by Django 5.2.4 on 2025-07-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_resource_receieved_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='receieved_date',
            new_name='received_date',
        ),
        migrations.AddField(
            model_name='product',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.resource'),
            preserve_default=False,
        ),
    ]
