# Generated by Django 5.2.4 on 2025-07-15 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_receieved_date_resource_received_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.AddField(
            model_name='transaction',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.resource'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
