# Generated by Django 5.2.4 on 2025-07-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_resource_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
